apiVersion: v1
kind: Service
metadata:
  name: elixir-test-service
spec:
  selector:
    app: elixir-test-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 4000 
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elixir-test-app
spec:
  selector:
    matchLabels:
      app: elixir-test-app
  replicas: 5
  template:
    metadata:
      labels:
        app: elixir-test-app
    spec:
      containers:
      - name: elixir-test-app
        image: gcr.io/timemanager-330915/timemanager_back:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
