apiVersion: v1
kind: Service
metadata:
  name: timemanager-back-service
spec:
  selector:
    app: timemanager-back-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: timemanager-back-app
spec:
  selector:
    matchLabels:
      app: timemanager-back-app
  replicas: 1
  template:
    metadata:
      labels:
        app: timemanager-back-app
    spec:
      containers:
      - name: timemanager-back-app
        image: gcr.io/timemanager-330915/timemanager_back:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
