apiVersion: v1
kind: Service
metadata:
  name: vue-test-service
spec:
  selector:
    app: vue-test-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment 
metadata:
  name: vue-test-app
spec:
  selector:
    matchLabels:
      app: vue-test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: vue-test-app
    spec:
      containers:
      - name: vue-test-app
        image: gcr.io/timemanager-330915/timemanager_front:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
