version: "3.9"
services:
  back:
    image: maelledefay/back
    build: 
      context: Back
    environment:
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      PGDATABASE: $PGDATABASE
      PGHOST: $PGHOST
      PGPORT: 5432
    ports:
      - 4000:4000
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
  front:
    image: maelledefay/front:dev
    build: 
      context: Front
      target: dev
    ports: 
      - 8080:8080
volumes:
  pgdata: